#!/bin/sh
set -e
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
if [ "$1" = "purge" ] ; then
	update-rc.d kvm-no-cloud-init-no-network remove >/dev/null
	update-rc.d kvm-no-cloud-init-network remove >/dev/null
fi
